# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

#POST http://localhost:18080/doSth.wlq
#Content-Type: application/x-www-form-urlencoded
#

POST http://localhost:18080/wl/testProject/doSomeThing/888
Content-Type: application/x-www-form-urlencoded

str={"name":"zhang", "id":1}&int=999&date=2018-08-08 05:37:33&arr=arr1&arr=arr2&vo={"name":"张三", "id":1}&volist=[{"id":9, "name":"zhang"},{"name":"li", "id":1}]

###